// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqrkerwdmjogcatmogcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxcmtlcndkbWpvZ2NhdG1vZ2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTUyODAsImV4cCI6MjA2NzM3MTI4MH0.qxWkd4MWZ28fVk3TE7692KF-KYOPpDtbJC0GXB8Akmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});